[SQUSH][DNM] Merge tag 'android-9.0.0_r16' into lineage-16.0
commit a8e07aecb24898d7d2b49cb785b0c193a4b134b4
Author: Roger Liao <rogerliao@google.com>
Date:   Wed Jul 4 12:27:34 2018 +0800

    Android.mk: add sdm710

    Fixes the following build error:
    error: update_engine_sideload (EXECUTABLES android-arm64) missing
    bootctrl.sdm710 (STATIC_LIBRARIES android-arm64)

    Bug: 111163725
    Change-Id: I82f2321d580cb2fdb15d2343e39abed5ccda50b1

Change-Id: I6a5dd86adae4886c4847f1ab7bbf7716c1cfcf76