Merge android-9.0.0_r12
commit 68e42f6258f63684559addfb107f884ec82a4d09
Merge: f687799 a8e07ae
Author: android-build-team Robot <android-build-team-robot@google.com>
Date:   Wed Jul 18 03:08:53 2018 +0000

    Snap for 4899218 from a8e07aecb24898d7d2b49cb785b0c193a4b134b4 to pi-dr1-release

    Change-Id: I9fb4cffa83625509c622653fea700ab93b46bc7f

commit a8e07aecb24898d7d2b49cb785b0c193a4b134b4
Author: Roger Liao <rogerliao@google.com>
Date:   Wed Jul 4 12:27:34 2018 +0800

    Android.mk: add sdm710

    Fixes the following build error:
    error: update_engine_sideload (EXECUTABLES android-arm64) missing
    bootctrl.sdm710 (STATIC_LIBRARIES android-arm64)

    Bug: 111163725
    Change-Id: I82f2321d580cb2fdb15d2343e39abed5ccda50b1

Change-Id: I3d3f7f710df8c9590776ebb686c83535716a7b9c